import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Text, StyleSheet, View, Modal, Pressable, Linking, TextInput, Clipboard } from 'react-native';
import Card from '../components/Card';
import Button from '../components/Button';
import Chip from '../components/Chip';
import Screen from '../components/Screen';
import { colors, spacing, typography } from '../theme/tokens';
import { useAppState } from '../context/AppState';
import rubricData from '../../data/writing_rubric.json';
import { checkOnlineFeedback, summarizeMatches, requestParaphrase } from '../utils/onlineFeedback';
import { getWordEntry } from '../utils/dictionary';
import { suggestSynonyms } from '../utils/synonymSuggest';
import { countWords } from '../utils/ys9Mock';
import { detectBasicErrors } from '../utils/basicErrorDetect';

function InlineFeedback({ report }) {
  if (!report?.inline_segments?.length) {
    return <Text style={styles.body}>{report?.inline_feedback || ''}</Text>;
  }
  return (
    <Text style={styles.body}>
      {report.inline_segments.map((seg, i) => (
        <Text
          key={`${i}-${seg.tag || 'plain'}`}
          style={[styles.inlineText, seg.tag ? styles[`tag_${seg.tag}`] : null]}
        >
          {seg.text}
        </Text>
      ))}
    </Text>
  );
}

export default function FeedbackScreen() {
  const { report, addUserWord, essayText, generateReport, level, writingEngine, setWritingEngine } = useAppState();
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [autoOnline, setAutoOnline] = useState(false);
  const wwItems = report?.ww_explanations || [];
  const nextSteps = report?.next_steps || [];
  const repetition = report?.repetition || [];
  const sourceText = essayText || report?.raw_text || report?.inline_feedback || '';
  const metrics = report?.metrics || { words: 0, sentences: 0, paragraphs: 0, avgSentence: 0 };
  const liveWordCount = countWords(sourceText);
  const liveCharCount = sourceText.length;
  const liveParagraphCount = sourceText.trim()
    ? sourceText.split(/\n{2,}/).map((p) => p.trim()).filter(Boolean).length
    : 0;
  const liveUniqueWords = sourceText.trim()
    ? new Set(
      sourceText
        .toLowerCase()
        .match(/[a-z']+/g) || []
    ).size
    : 0;
  const estReadMinutes = liveWordCount > 0 ? Math.max(1, Math.round(liveWordCount / 180)) : 0;
  const levelWordTarget = { P1: 80, P2: 120, P3: 180, P4: 250 }[String(level || '').toUpperCase()] || 150;
  const targetDelta = liveWordCount - levelWordTarget;
  const targetState = targetDelta >= 0 ? 'On target' : `${Math.abs(targetDelta)} words below target`;
  const criteria = report?.criteria_flags || null;
  const strengths = report?.strengths || [];
  const issues = report?.issues || [];
  const diagnostics = report?.diagnostics || [];
  const sentenceFeedback = report?.sentence_feedback || [];
  const paragraphFeedback = report?.paragraph_feedback || [];
  const priorityFixes = report?.priority_fixes || [];
  const cohesionStats = report?.cohesion_stats || { linkers: 0, cohesionScore: 0, used: [] };
  const sentenceCorrections = report?.sentence_corrections || [];
  const criticalErrors = report?.critical_errors || [];
  const scaffold = report?.scaffold || [];
  const scaffoldExamples = report?.scaffold_examples || [];
  const thesisSuggestions = report?.thesis_suggestions || [];
  const claimEvidence = report?.claimEvidence || { claimCount: 0, evidenceCount: 0 };
  const checklistGaps = report?.checklist_gaps || [];
  const styleFeedback = report?.style_feedback || [];
  const weakWords = report?.weak_words || []
  const keywordCoverage = report?.keyword_coverage || { total: 0, used: 0, hits: [] };
  const structure = report?.structure || { hasIntroSignal: false, hasConclusionSignal: false, paraCount: 0 };
  const cohesionAdvice = report?.cohesion_advice || [];
  const rubric = report?.rubric || { Grammar: 0, Vocabulary: 0, Organization: 0, Content: 0, Mechanics: 0, Total: 0 };
  const writing9 = report?.writing9_style || null;
  const paraphraseBank = report?.paraphrase_bank || [];
  const variantDiffs = report?.revised_variant_diffs || [];
  const cefrSummary = report?.cefr_summary || [];
  const [onlineStatus, setOnlineStatus] = useState("idle");
  const [onlineBuckets, setOnlineBuckets] = useState({ Grammar: [], Vocabulary: [], Mechanics: [], Style: [] });
  const [onlineSummary, setOnlineSummary] = useState(null);
  const [showAllOnline, setShowAllOnline] = useState(false);
  const [onlineError, setOnlineError] = useState("");
  const [onlineSegments, setOnlineSegments] = useState([]);
  const [onlineRevised, setOnlineRevised] = useState("");
  const [activeMatch, setActiveMatch] = useState(null);
  const [paraphraseModal, setParaphraseModal] = useState(null);
  const [onlineMatchStates, setOnlineMatchStates] = useState({});
  const [paraphraseStatus, setParaphraseStatus] = useState('idle');
  const [paraphraseError, setParaphraseError] = useState('');
  const [paraphrases, setParaphrases] = useState([]);
  const [synonymInput, setSynonymInput] = useState('');
  const [synonymResults, setSynonymResults] = useState([]);
  const [grammarPluginEnabled, setGrammarPluginEnabled] = useState(true);
  const grammarPluginIssues = useMemo(() => detectBasicErrors(sourceText), [sourceText]);
  const ENGINES = [
    { key: 'hybrid', label: 'Hybrid (Best)' },
    { key: 'online', label: 'Online (LanguageTool)' },
    { key: 'local', label: 'Local (Rule-based)' }
  ];
  useEffect(() => {
    if (!report && essayText && !autoGenerated) {
      generateReport({ text: essayText, type: "general", level });
      setAutoGenerated(true);
    }
  }, [report, essayText, autoGenerated, generateReport, level]);
  const applyOnlineFixes = (text, matches = []) => {
    if (!text) return '';
    const usable = matches
      .filter((m) => typeof m.offset === 'number' && typeof m.length === 'number' && m.replacements?.length)
      .sort((a, b) => b.offset - a.offset);
    let out = text;
    usable.forEach((m) => {
      const rep = m.replacements[0]?.value;
      if (!rep) return;
      out = out.slice(0, m.offset) + rep + out.slice(m.offset + m.length);
    });
    return out;
  };
  const applyOnlineFixesWithState = (text, matches = [], stateMap = {}) => {
    if (!text) return '';
    const usable = matches
      .filter((m, idx) => {
        if (!(typeof m.offset === 'number' && typeof m.length === 'number' && m.replacements?.length)) return false;
        const key = `${m.offset}-${m.length}-${idx}`;
        return stateMap[key] !== 'rejected';
      })
      .sort((a, b) => b.offset - a.offset);
    let out = text;
    usable.forEach((m) => {
      const rep = m.replacements[0]?.value;
      if (!rep) return;
      out = out.slice(0, m.offset) + rep + out.slice(m.offset + m.length);
    });
    return out;
  };

  const splitSentences = (text) => {
    const safe = String(text || '').trim();
    if (!safe) return [];
    const parts = safe.match(/[^.!?]+[.!?]*/g);
    if (!parts) return [safe];
    const seen = new Set();
    return parts
      .map((s) => s.trim())
      .filter((s) => s.length > 15)
      .filter((s) => {
        const key = s.toLowerCase();
        if (seen.has(key)) return false;
        seen.add(key);
        return true;
      });
  };

  const runParaphrase = useCallback(async () => {
    try {
      setParaphraseStatus('loading');
      setParaphraseError('');
      const source = essayText || report?.raw_text || report?.inline_feedback || '';
      if (!source.trim()) {
        setParaphraseStatus('error');
        setParaphraseError('No text to paraphrase.');
        return;
      }
      const sentences = splitSentences(source).slice(0, 12);
      const res = await requestParaphrase(sentences);
      setParaphrases(res || []);
      setParaphraseStatus('done');
    } catch (e) {
      setParaphraseStatus('error');
      setParaphraseError(e.message || 'Paraphrase failed');
    }
  }, [report, essayText]);

  const formatOnlineMatch = (m) => {
    const ctx = m.context || {};
    const snippet = ctx.text || '';
    const bad = snippet && typeof ctx.offset === 'number' ? snippet.slice(ctx.offset, ctx.offset + ctx.length) : '';
    const entry = bad ? getWordEntry(bad.toLowerCase()) : null;
    const synonyms = entry?.synonyms?.slice(0, 4) || [];
    return {
      bad,
      message: m.message,
      replacements: (m.replacements || []).slice(0, 4).map((r) => r.value),
      synonyms
    };
  };

  const runOnlineFeedback = useCallback(async () => {
    try {
      setOnlineStatus("loading");
      setOnlineError("");
      const sourceDraft = essayText || report?.raw_text || report?.inline_feedback || '';
      if (!sourceDraft.trim()) {
        setOnlineStatus("error");
        setOnlineError("No text to send.");
        return;
      }
      if (sourceDraft.length > 20000) {
        setOnlineStatus("error");
        setOnlineError("Text too long for free online feedback (20,000 chars max).");
        return;
      }
      const res = await checkOnlineFeedback(sourceDraft);
      const matches = res.matches || [];
      const summary = summarizeMatches(matches);
      setOnlineBuckets(summary.buckets);
      setOnlineSummary(summary);
      const sorted = matches
        .filter((m) => typeof m.offset === 'number' && typeof m.length === 'number')
        .sort((a, b) => a.offset - b.offset);
      let cursor = 0;
      const segs = [];
      sorted.forEach((m) => {
        const start = m.offset;
        const end = m.offset + m.length;
        const cat = (m.rule?.category?.id || m.rule?.category?.name || '').toLowerCase();
        const tag = cat.includes('grammar') || cat.includes('syntax')
          ? 'grammar'
          : (cat.includes('style') || cat.includes('word') || cat.includes('vocab') ? 'vocab' : 'mechanics');
        if (start > cursor) segs.push({ text: sourceDraft.slice(cursor, start) });
        segs.push({ text: sourceDraft.slice(start, end), tag, match: m });
        cursor = end;
      });
      if (cursor < sourceDraft.length) segs.push({ text: sourceDraft.slice(cursor) });
      setOnlineSegments(segs);
      const initialState = {};
      matches.forEach((m, idx) => {
        if (typeof m.offset === 'number' && typeof m.length === 'number') {
          initialState[`${m.offset}-${m.length}-${idx}`] = 'pending';
        }
      });
      setOnlineMatchStates(initialState);
      setOnlineRevised(applyOnlineFixes(sourceDraft, matches));
      setOnlineStatus("done");
    } catch (e) {
      setOnlineStatus("error");
      setOnlineError(e.message || "Online feedback failed");
    }
  }, [report, essayText]);
  useEffect(() => {
    if (report && onlineStatus === "idle" && !autoOnline && writingEngine !== 'local') {
      setAutoOnline(true);
      runOnlineFeedback();
    }
  }, [report, onlineStatus, autoOnline, writingEngine, runOnlineFeedback]);

  const saveRepeatedWords = () => {
    repetition.forEach((r) => addUserWord(r.word));
  };
  const saveParaphraseWords = () => {
    paraphraseBank.forEach((p) => addUserWord(p.word));
  };
  const runSynonymLookup = () => {
    const term = synonymInput.trim().toLowerCase();
    if (!term) {
      setSynonymResults([]);
      return;
    }
    const entry = getWordEntry(term);
    const fromEntry = entry?.synonyms || [];
    if (fromEntry.length > 0) {
      setSynonymResults(fromEntry.slice(0, 10));
      return;
    }
    const fallback = suggestSynonyms(term) || [];
    setSynonymResults(fallback.slice(0, 10));
  };

  const buildExample = (word, synonym) => {
    const base = word || 'word';
    const syn = synonym || word;
    return `Using “${syn}” instead of “${base}” can improve academic tone.`;
  };
  const findExampleSentence = (fullText, term) => {
    if (!fullText || !term) return '';
    const parts = fullText.match(/[^.!?]+[.!?]*/g);
    const sentences = (parts || [fullText]).map((s) => s.trim()).filter(Boolean);
    const safe = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const re = new RegExp(`\\b${safe}\\b`, 'i');
    return sentences.find((s) => re.test(s)) || '';
  };
  const totalOnlineIssues = onlineBuckets.Grammar.length + onlineBuckets.Vocabulary.length + onlineBuckets.Mechanics.length + onlineBuckets.Style.length;
  const onlineScore = Math.max(0, 20 - Math.min(10, Math.round(totalOnlineIssues / 2)));
  const hybridScore = Math.round((rubric.Total + onlineScore) / 2);
  const currentMatchKey = (m) => {
    if (!m) return '';
    const idx = m.__idx ?? 0;
    return `${m.offset}-${m.length}-${idx}`;
  };
  const setMatchState = (m, state) => {
    if (!m) return;
    const key = currentMatchKey(m);
    setOnlineMatchStates((prev) => ({ ...prev, [key]: state }));
  };
  useEffect(() => {
    const baseText = essayText || report?.raw_text || report?.inline_feedback || '';
    if (!baseText) return;
    const matches = onlineSegments.filter((s) => s.match).map((s) => s.match);
    if (!matches.length) return;
    setOnlineRevised(applyOnlineFixesWithState(baseText, matches, onlineMatchStates || {}));
  }, [onlineMatchStates, onlineSegments, report, essayText]);

  return (
    <Screen scroll contentStyle={styles.content}>
      <Text style={styles.h1}>BUEPT Writing Feedback</Text>
      <Card style={styles.card}>
        <Text style={styles.h3}>Quick Actions</Text>
        <Text style={styles.sub}>Run checks or generate paraphrase without scrolling.</Text>
        <View style={styles.saveRow}>
          <Button
            label={onlineStatus === 'loading' ? 'Checking...' : 'Run Online'}
            variant="secondary"
            onPress={runOnlineFeedback}
            disabled={onlineStatus === 'loading' || writingEngine === 'local'}
          />
          <Button
            label={paraphraseStatus === 'loading' ? 'Paraphrasing...' : 'Paraphrase'}
            onPress={runParaphrase}
            disabled={paraphraseStatus === 'loading'}
          />
        </View>
      </Card>

      <Card style={styles.card}>
        <Text style={styles.h3}>Writing Model</Text>
        <View style={styles.chips}>
          {ENGINES.map((e) => (
            <Chip
              key={e.key}
              label={e.label}
              active={writingEngine === e.key}
              onPress={() => setWritingEngine(e.key)}
            />
          ))}
        </View>
        <Text style={styles.sub}>
          {writingEngine === 'hybrid' && 'Hybrid = Local rubric + Online checks'}
          {writingEngine === 'online' && 'Online = LanguageTool only'}
          {writingEngine === 'local' && 'Local = Offline rule-based only'}
        </Text>
      </Card>

      <Card style={styles.card}>
        <Text style={styles.h3}>Word Count & Readiness</Text>
        <Text style={styles.body}>
          Words: {liveWordCount} • Unique: {liveUniqueWords} • Characters: {liveCharCount}
        </Text>
        <Text style={styles.sub}>
          Paragraphs: {liveParagraphCount} • Est. read time: {estReadMinutes ? `${estReadMinutes} min` : '0 min'}
        </Text>
        <Text style={styles.sub}>
          Level target ({String(level || '').toUpperCase()}): {levelWordTarget} • {targetState}
        </Text>
      </Card>

      <Card style={styles.card}>
        <View style={styles.saveRow}>
          <Text style={styles.h3}>Auto Grammar Plugin</Text>
          <Button
            label={grammarPluginEnabled ? 'On' : 'Off'}
            variant={grammarPluginEnabled ? 'primary' : 'secondary'}
            onPress={() => setGrammarPluginEnabled((v) => !v)}
          />
        </View>
        {grammarPluginEnabled ? (
          grammarPluginIssues.length > 0 ? (
            grammarPluginIssues.slice(0, 12).map((issue, idx) => (
              <Text key={idx} style={styles.body}>• {issue}</Text>
            ))
          ) : (
            <Text style={styles.sub}>No basic grammar issue detected.</Text>
          )
        ) : (
          <Text style={styles.sub}>Plugin is disabled.</Text>
        )}
      </Card>

      <Card style={styles.card}>
        <Text style={styles.h3}>Synonym Finder</Text>
        <Text style={styles.sub}>Type one word and get quick synonyms.</Text>
        <TextInput
          style={styles.input}
          value={synonymInput}
          onChangeText={setSynonymInput}
          placeholder="Enter a word (e.g. important)"
          placeholderTextColor={colors.muted}
          autoCapitalize="none"
        />
        <View style={styles.saveRow}>
          <Button label="Find Synonyms" variant="secondary" onPress={runSynonymLookup} />
        </View>
        {synonymResults.length > 0 ? (
          <Text style={styles.body}>Suggestions: {synonymResults.join(', ')}</Text>
        ) : (
          <Text style={styles.sub}>No result yet.</Text>
        )}
      </Card>

      {writingEngine !== 'online' && report && (
        <>
          <Card style={styles.card}>
            <Text style={styles.h3}>Section 1 – Bravo</Text>
            <Text style={styles.body}>{report.bravo}</Text>
            {report.type && <Text style={styles.sub}>Type: {report.type}</Text>}
          </Card>

          <Card style={styles.card}>
            <Text style={styles.h3}>Writing Snapshot</Text>
            <Text style={styles.body}>Words: {metrics.words} • Sentences: {metrics.sentences} • Paragraphs: {metrics.paragraphs} • Avg sentence: {metrics.avgSentence}</Text>
            <Text style={styles.sub}>Live word count: {liveWordCount}</Text>
            <Text style={styles.sub}>Lexical variety (TTR): {metrics.ttr} • Academic words: {metrics.academicCount}</Text>
            <Text style={styles.sub}>Cohesion: {cohesionStats.cohesionScore}/4 • Linkers: {cohesionStats.linkers}</Text>
            {cohesionStats.used?.length > 0 && (
              <Text style={styles.sub}>Used linkers: {cohesionStats.used.join(', ')}</Text>
            )}
            <Text style={styles.sub}>Claims: {claimEvidence.claimCount} • Evidence: {claimEvidence.evidenceCount}</Text>
            <Text style={styles.sub}>Intro signal: {structure.hasIntroSignal ? 'Yes' : 'No'} • Conclusion signal: {structure.hasConclusionSignal ? 'Yes' : 'No'}</Text>
            {keywordCoverage.total > 0 && (
              <Text style={styles.sub}>
                Keyword coverage: {keywordCoverage.used}/{keywordCoverage.total} ({keywordCoverage.hits.join(', ') || '—'})
              </Text>
            )}
          </Card>

          <Card style={styles.card}>
            <Text style={styles.h3}>Paraphrase Sentences (API)</Text>
            <Text style={styles.sub}>Generate paraphrases for your sentences using the feedback API.</Text>
            <Button
              label={paraphraseStatus === 'loading' ? 'Paraphrasing...' : 'Generate Paraphrases'}
              onPress={runParaphrase}
              disabled={paraphraseStatus === 'loading'}
            />
            {paraphraseError ? <Text style={styles.sub}>Error: {paraphraseError}</Text> : null}
          {paraphraseStatus === 'done' && paraphrases.length > 0 && (
              <View>
                {paraphrases.map((p, i) => {
                  const original = typeof p === 'string' ? '' : (p.original || p.source || p.text || '');
                  const para = typeof p === 'string' ? p : (p.paraphrase || p.result || p.alt || p.output || '');
                  return (
                    <View key={i} style={styles.resultItem}>
                      {original ? <Text style={styles.sub}>Original: {original}</Text> : <Text style={styles.sub}>Sentence #{i + 1}</Text>}
                      <Text style={styles.body}>Paraphrase: {para}</Text>
                    </View>
                  );
                })}
                <Text style={styles.sub}>Tip: paraphrases are suggestions; keep your original meaning while revising.</Text>
              </View>
            )}
          </Card>

          <Card style={styles.card}>
            <Text style={styles.h3}>Strengths</Text>
            {strengths.map((s, i) => (
              <Text key={i} style={styles.body}>• {s}</Text>
            ))}
          </Card>

          <Card style={styles.card}>
            <Text style={styles.h3}>Key Issues</Text>
            {issues.map((s, i) => (
              <Text key={i} style={styles.body}>• {s}</Text>
            ))}
          </Card>

          {priorityFixes.length > 0 && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Priority Fixes</Text>
              {priorityFixes.map((s, i) => (
                <Text key={i} style={styles.body}>• {s}</Text>
              ))}
            </Card>
          )}

          {diagnostics.length > 0 && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Diagnostics</Text>
              {diagnostics.map((s, i) => (
                <Text key={i} style={styles.body}>• {s}</Text>
              ))}
            </Card>
          )}

          {criticalErrors.length > 0 && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Critical Errors (Top 15)</Text>
              {criticalErrors.map((e, i) => (
                <View key={i} style={styles.block}>
                  <Text style={styles.body}>• {e.text} ({e.tag})</Text>
                  <Text style={styles.sub}>{e.why}</Text>
                  <Text style={styles.sub}>Fix: {e.suggestion}</Text>
                </View>
              ))}
            </Card>
          )}

          {sentenceFeedback.length > 0 && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Sentence-Level Fixes</Text>
              {sentenceFeedback.map((f, i) => (
                <View key={i} style={styles.block}>
                  <Text style={styles.body}>• {f.issue}</Text>
                  <Text style={styles.sub}>“{f.sentence}”</Text>
                  <Text style={styles.sub}>Fix: {f.fix}</Text>
                </View>
              ))}
            </Card>
          )}

          {sentenceCorrections.length > 0 && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Sentence Corrections (Highlighted)</Text>
              {sentenceCorrections.map((s, i) => (
                <View key={i} style={styles.block}>
                  <Text style={styles.body}>Original: “{s.sentence}”</Text>
                  <Text style={styles.sub}>Revised: “{s.revised}”</Text>
                  {s.tags?.length > 0 && (
                    <View style={styles.tagRow}>
                      {s.tags.map((t) => (
                        <View key={`${i}-${t}`} style={[styles.tagChip, styles[`tag_${t}`]]}>
                          <Text style={styles.tagText}>{t.toUpperCase()}</Text>
                        </View>
                      ))}
                    </View>
                  )}
                  {s.reasons?.length > 0 && (
                    <Text style={styles.sub}>Why: {s.reasons.join(' | ')}</Text>
                  )}
                </View>
              ))}
            </Card>
          )}

          {paragraphFeedback.length > 0 && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Paragraph Diagnostics</Text>
              {paragraphFeedback.map((p) => (
                <View key={p.index} style={styles.block}>
                  <Text style={styles.body}>Paragraph {p.index}: {p.length} sentence(s)</Text>
                  <Text style={styles.sub}>Topic sentence: {p.hasTopic ? 'Yes' : 'No'}</Text>
                  <Text style={styles.sub}>Example present: {p.hasExample ? 'Yes' : 'No'}</Text>
                  <Text style={styles.sub}>Concluding sentence: {p.hasConcluding ? 'Yes' : 'No'}</Text>
                </View>
              ))}
            </Card>
          )}


          {scaffold.length > 0 && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Ideal Structure (Scaffold)</Text>
              {scaffold.map((s, i) => (
                <Text key={i} style={styles.body}>• {s}</Text>
              ))}
            </Card>
          )}

          {scaffoldExamples.length > 0 && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Scaffold Examples</Text>
              {scaffoldExamples.map((s, i) => (
                <Text key={i} style={styles.body}>• {s}</Text>
              ))}
            </Card>
          )}

          {thesisSuggestions.length > 0 && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Thesis Suggestions</Text>
              {thesisSuggestions.map((s, i) => (
                <Text key={i} style={styles.body}>• {s}</Text>
              ))}
            </Card>
          )}

          {checklistGaps.length > 0 && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Checklist Gaps</Text>
              {checklistGaps.map((s, i) => (
                <Text key={i} style={styles.body}>• {s}</Text>
              ))}
            </Card>
          )}

          {styleFeedback.length > 0 && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Style Feedback</Text>
              {styleFeedback.map((s, i) => (
                <Text key={i} style={styles.body}>• {s}</Text>
              ))}
            </Card>
          )}

          {weakWords.length > 0 && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Weak Word Replacements</Text>
              {weakWords.map((w, i) => (
                <Text key={i} style={styles.body}>
                  • {w.word} ({w.count}) → {w.synonyms.length ? w.synonyms.join(', ') : 'synonyms pending'}
                </Text>
              ))}
            </Card>
          )}

          {cohesionAdvice.length > 0 && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Cohesion Advice</Text>
              {cohesionAdvice.map((s, i) => (
                <Text key={i} style={styles.body}>• {s}</Text>
              ))}
            </Card>
          )}


          <Card style={styles.card}>
            <Text style={styles.h3}>Section 2 – Inline Feedback</Text>
            <InlineFeedback report={report} />
            {report.inline_legend && (
              <View style={styles.legend}>
                {Object.entries(report.inline_legend).map(([k, label]) => (
                  <View key={k} style={styles.legendItem}>
                    <View style={[styles.legendSwatch, styles[`tag_${k}`]]} />
                    <Text style={styles.legendLabel}>
                      {label}{report.error_summary?.[k] ? ` (${report.error_summary[k]})` : ''}
                    </Text>
                  </View>
                ))}
              </View>
            )}
            <View style={styles.block}>
              <Text style={styles.h4}>Wrong Word Choice (ww)</Text>
              {wwItems.map((w, i) => (
                <Text key={i} style={styles.body}>
                  {w.wrong} → {w.better.join(', ')} ({w.why})
                </Text>
              ))}
            </View>
          </Card>

          <Card style={[styles.card, styles.revisedCard]}>
            <View style={styles.revisedHeader}>
              <Text style={styles.h3}>✍️ Improved Version</Text>
              <Pressable
                onPress={() => Clipboard.setString(report.revised || '')}
                style={styles.copyBtn}
              >
                <Text style={styles.copyBtnText}>📋 Copy</Text>
              </Pressable>
            </View>
            <Text style={styles.revisedText}>{report.revised}</Text>
          </Card>

          {report.revised_advanced ? (
            <Card style={styles.card}>
              <Text style={styles.h3}>Section 3b – Revised Version (Advanced)</Text>
              <Text style={styles.body}>{report.revised_advanced}</Text>
            </Card>
          ) : null}

          {report.revised_variants?.length ? (
            <Card style={styles.card}>
              <Text style={styles.h3}>Section 3c – Alternative Rewrites</Text>
              {report.revised_variants.map((v, i) => (
                <View key={i} style={styles.block}>
                  <Text style={styles.sub}>Variant {i + 1}</Text>
                  <Text style={styles.body}>{v}</Text>
                  {variantDiffs[i]?.added?.length ? (
                    <View style={styles.tagRow}>
                      {variantDiffs[i].added.map((w) => (
                        <View key={`${i}-${w}`} style={styles.wordChip}>
                          <Text style={styles.wordChipText}>{w}</Text>
                        </View>
                      ))}
                    </View>
                  ) : null}
                </View>
              ))}
            </Card>
          ) : null}

          <Card style={styles.card}>
            <Text style={styles.h3}>Section 4 – Next Step</Text>
            {nextSteps.map((s, i) => (
              <Text key={i} style={styles.body}>• {s}</Text>
            ))}
          </Card>

          <Card style={styles.card}>
            <Text style={styles.h3}>📊 {rubricData.title}</Text>
            {/* Total score prominent display */}
            <View style={styles.totalScoreRow}>
              <Text style={styles.totalScoreNum}>{rubric.Total}</Text>
              <Text style={styles.totalScoreDenom}>/20</Text>
              <Text style={styles.totalScoreLabel}>{rubric.Total >= 16 ? '🏆 Excellent' : rubric.Total >= 12 ? '✅ Good' : rubric.Total >= 8 ? '⚠️ Fair' : '📝 Needs Work'}</Text>
            </View>
            {rubricData.categories.map((c) => {
              const score = rubric[c.name] || 0;
              const pct = (score / c.max) * 100;
              const barColor = pct >= 75 ? '#4CAF50' : pct >= 50 ? '#FF9800' : '#F44336';
              return (
                <View key={c.name} style={styles.rubricItem}>
                  <View style={styles.rubricLabelRow}>
                    <Text style={styles.rubricName}>{c.name}</Text>
                    <Text style={styles.rubricScore}>{score}/{c.max}</Text>
                  </View>
                  <View style={styles.progressTrack}>
                    <View style={[styles.progressFill, { width: `${pct}%`, backgroundColor: barColor }]} />
                  </View>
                  <Text style={styles.rubricDesc}>{c.desc}</Text>
                </View>
              );
            })}
          </Card>

          {writing9 && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Overall Band Score</Text>
              <Text style={styles.body}>Band: {writing9.band} • CEFR: {report.cefr} • Score: {rubric.Total}/20</Text>
              {writing9.overall_comment ? <Text style={styles.sub}>{writing9.overall_comment}</Text> : null}
              {Object.entries(writing9.criteria).map(([k, v]) => (
                <Text key={k} style={styles.body}>{k}: {v}</Text>
              ))}
              {writing9.band_descriptors && (
                <View style={styles.block}>
                  <Text style={styles.h4}>Band Descriptors</Text>
                  {Object.entries(writing9.band_descriptors).map(([k, v]) => (
                    <Text key={k} style={styles.sub}>• {k}: {v}</Text>
                  ))}
                </View>
              )}
              {writing9.criteria_comments && (
                <View style={styles.block}>
                  <Text style={styles.h4}>Band‑Style Comments</Text>
                  {Object.entries(writing9.criteria_comments).map(([k, list]) => (
                    <View key={k} style={styles.block}>
                      <Text style={styles.body}>• {k}</Text>
                      {(list || []).map((c, i) => (
                        <Text key={`${k}-${i}`} style={styles.sub}>- {c}</Text>
                      ))}
                    </View>
                  ))}
                </View>
              )}
            </Card>
          )}

          {criteria && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Criteria Checklist</Text>
              <Text style={styles.h4}>Task Achievement</Text>
              <Text style={styles.body}>• Complete response: {criteria.task.completeResponse ? 'Yes' : 'No'}</Text>
              <Text style={styles.body}>• Appropriate word count: {criteria.task.appropriateWordCount ? 'Yes' : 'No'}</Text>
              <Text style={styles.body}>• Words: {metrics.words}</Text>
              <Text style={styles.body}>• Paragraphs (3+): {criteria.task.paragraphs ? 'Yes' : 'No'}</Text>
              <Text style={styles.body}>• Clear and comprehensive ideas: {criteria.task.clearIdeas ? 'Yes' : 'No'}</Text>
              <Text style={styles.body}>• Relevant examples: {criteria.task.relevantExamples ? 'Yes' : 'No'}</Text>

              <Text style={styles.h4}>Coherence & Cohesion</Text>
              <Text style={styles.body}>• Logical structure: {criteria.cohesion.logicalStructure ? 'Yes' : 'No'}</Text>
              <Text style={styles.body}>• Introduction & conclusion: {criteria.cohesion.introConclusion ? 'Yes' : 'No'}</Text>
              <Text style={styles.body}>• Supported main points: {criteria.cohesion.supportedMainPoints ? 'Yes' : 'No'}</Text>
              <Text style={styles.body}>• Accurate linking words: {criteria.cohesion.accurateLinkingWords ? 'Yes' : 'No'}</Text>
              <Text style={styles.body}>• Variety in linkers: {criteria.cohesion.varietyInLinkingWords ? 'Yes' : 'No'}</Text>

              <Text style={styles.h4}>Lexical Resource</Text>
              <Text style={styles.body}>• Varied vocabulary: {criteria.lexical.variedVocabulary ? 'Yes' : 'No'}</Text>
              <Text style={styles.body}>• Word form/spelling OK: {criteria.lexical.spellingWordForm ? 'Yes' : 'No'}</Text>

              <Text style={styles.h4}>Grammar Range & Accuracy</Text>
              <Text style={styles.body}>• Mix of complex/simple sentences: {criteria.grammar.mixComplexSimple ? 'Yes' : 'No'}</Text>
              <Text style={styles.body}>• Grammar mostly correct: {criteria.grammar.clearCorrectGrammar ? 'Yes' : 'No'}</Text>
            </Card>
          )}

          <Card style={styles.card}>
            <Text style={styles.h3}>Online Feedback (Free API)</Text>
            <Text style={styles.body}>Uses LanguageTool free API for extra checks.</Text>
            <Pressable onPress={() => Linking.openURL('https://languagetool.org')}>
              <Text style={styles.link}>Powered by LanguageTool</Text>
            </Pressable>
            <Button
              label={writingEngine === 'local' ? 'Online Disabled (Local Only)' : (onlineStatus === 'loading' ? 'Checking…' : 'Run Online Feedback')}
              onPress={runOnlineFeedback}
              disabled={onlineStatus === 'loading' || writingEngine === 'local'}
            />
            {onlineError ? <Text style={styles.sub}>Error: {onlineError}</Text> : null}
            {onlineStatus === 'done' && (
              <View style={styles.block}>
                <Text style={styles.h4}>Online Matches (Rubric-Aligned)</Text>
                <Text style={styles.body}>
                  Grammar: {onlineBuckets.Grammar.length} •
                  Vocabulary: {onlineBuckets.Vocabulary.length} •
                  Mechanics: {onlineBuckets.Mechanics.length} •
                  Style: {onlineBuckets.Style.length}
                </Text>
                {onlineSummary ? (
                  <Text style={styles.sub}>Total issues: {onlineSummary.total}</Text>
                ) : null}
                <View style={styles.onlineActions}>
                  <Button
                    label="Apply All"
                    onPress={() => {
                      const next = {};
                      Object.keys(onlineMatchStates || {}).forEach((k) => { next[k] = 'accepted'; });
                      setOnlineMatchStates(next);
                    }}
                  />
                  <Button
                    label="Reject All"
                    variant="secondary"
                    onPress={() => {
                      const next = {};
                      Object.keys(onlineMatchStates || {}).forEach((k) => { next[k] = 'rejected'; });
                      setOnlineMatchStates(next);
                    }}
                  />
                </View>
                <Button
                  label={showAllOnline ? 'Hide Details' : 'Show All Online Issues'}
                  variant="secondary"
                  onPress={() => setShowAllOnline((v) => !v)}
                />

                {['Grammar', 'Vocabulary', 'Mechanics', 'Style'].map((k) => (
                  <View key={k} style={styles.block}>
                    <Text style={styles.h4}>{k}</Text>
                    {(showAllOnline ? onlineBuckets[k] : onlineBuckets[k].slice(0, 4)).map((m, i) => {
                      const fm = formatOnlineMatch(m);
                      return (
                        <View key={`${k}-${i}`} style={[styles.onlineItem, styles[`online_${k.toLowerCase()}`]]}>
                          <Text style={styles.body}>• {fm.message}</Text>
                          {fm.bad ? <Text style={styles.sub}>Issue: “{fm.bad}”</Text> : null}
                          {fm.replacements.length > 0 && (
                            <Text style={styles.sub}>Suggestions: {fm.replacements.join(', ')}</Text>
                          )}
                          {fm.synonyms.length > 0 && (
                            <Text style={styles.sub}>Synonyms: {fm.synonyms.join(', ')}</Text>
                          )}
                        </View>
                      );
                    })}
                    {!showAllOnline && onlineBuckets[k].length > 4 && (
                      <Text style={styles.sub}>+ {onlineBuckets[k].length - 4} more</Text>
                    )}
                  </View>
                ))}
              </View>
            )}
            {writingEngine === 'hybrid' && onlineStatus === 'done' && (
              <View style={styles.block}>
                <Text style={styles.h4}>Hybrid Score</Text>
                <Text style={styles.body}>Local Score: {rubric.Total}/20</Text>
                <Text style={styles.body}>Online Score: {onlineScore}/20</Text>
                <Text style={styles.body}>Hybrid Total: {hybridScore}/20</Text>
              </View>
            )}
            {onlineStatus === 'done' && onlineSegments.length > 0 && (
              <View style={styles.block}>
                <Text style={styles.h4}>Highlighted Online Issues</Text>
                <Text style={styles.body}>
                  {onlineSegments.map((seg, i) => (
                    seg.tag ? (
                      <Text
                        key={`${i}-${seg.tag || 'plain'}`}
                        style={[styles.inlinePress, styles[`online_${seg.tag}`]]}
                        onPress={() => setActiveMatch({ ...seg.match, __idx: i })}
                      >
                        {seg.text}
                      </Text>
                    ) : (
                      <Text key={`${i}-${seg.tag || 'plain'}`}>{seg.text}</Text>
                    )
                  ))}
                </Text>
              </View>
            )}
            {onlineStatus === 'done' && onlineRevised ? (
              <View style={styles.block}>
                <Text style={styles.h4}>Auto Revised Version (Online)</Text>
                <Text style={styles.body}>{onlineRevised}</Text>
              </View>
            ) : null}
          </Card>

          {paraphraseBank.length > 0 && (
            <Card style={styles.card}>
              <Text style={styles.h3}>Paraphrase Bank</Text>
              {paraphraseBank.map((p, i) => (
                <View key={i} style={styles.block}>
                  <Text style={styles.body}>{p.word}</Text>
                  <View style={styles.tagRow}>
                    {p.synonyms.slice(0, 6).map((s) => (
                      <Pressable key={`${p.word}-${s}`} onPress={() => setParaphraseModal({ word: p.word, synonym: s })} style={styles.wordChipAlt}>
                        <Text style={styles.wordChipText}>{s}</Text>
                      </Pressable>
                    ))}
                  </View>
                </View>
              ))}
              <View style={styles.saveRow}>
                <Button label="Save Paraphrase Words" onPress={saveParaphraseWords} />
              </View>
            </Card>
          )}

          <Card style={styles.card}>
            <Text style={styles.h3}>CEFR Summary</Text>
            <Text style={styles.body}>{report.cefr}</Text>
            {cefrSummary.length > 0 && (
              <View style={styles.block}>
                {cefrSummary.map((s, i) => (
                  <Text key={i} style={styles.sub}>{s}</Text>
                ))}
              </View>
            )}
          </Card>

          <Card style={styles.card}>
            <Text style={styles.h3}>Repetition & Synonyms</Text>
            {repetition.map((r, i) => (
              <Text key={i} style={styles.body}>
                {r.word} → {r.synonyms.length ? r.synonyms.join(', ') : 'synonyms pending'}
              </Text>
            ))}
            <View style={styles.saveRow}>
              <Button label="Save Words" onPress={saveRepeatedWords} />
            </View>
          </Card>
        </>
      )}

      {writingEngine === 'online' && (
        <Card style={styles.card}>
          <Text style={styles.h3}>Online-Only Mode</Text>
          <Text style={styles.body}>Local rubric and offline feedback are hidden. Only online results are shown.</Text>
        </Card>
      )}


      <Modal visible={!!paraphraseModal} transparent animationType="fade">
        <Pressable style={styles.modalBackdrop} onPress={() => setParaphraseModal(null)}>
          <Pressable style={styles.modalCard} onPress={() => { }}>
            <Text style={styles.h3}>Paraphrase Example</Text>
            {paraphraseModal ? (
              <>
                <Text style={styles.body}>Word: {paraphraseModal.word}</Text>
                <Text style={styles.body}>Synonym: {paraphraseModal.synonym}</Text>
                {(() => {
                  const source = essayText || report?.raw_text || report?.inline_feedback || '';
                  const example = findExampleSentence(source, paraphraseModal.word) || findExampleSentence(source, paraphraseModal.synonym);
                  return example ? (
                    <Text style={styles.sub}>Example: {example}</Text>
                  ) : (
                    <Text style={styles.sub}>{buildExample(paraphraseModal.word, paraphraseModal.synonym)}</Text>
                  );
                })()}
              </>
            ) : null}
            <View style={styles.modalActions}>
              <Button label="Add to Vocab" onPress={() => {
                if (paraphraseModal?.word) addUserWord(paraphraseModal.word);
                if (paraphraseModal?.synonym) addUserWord(paraphraseModal.synonym);
                setParaphraseModal(null);
              }} />
              <Button label="Close" variant="ghost" onPress={() => setParaphraseModal(null)} />
            </View>
          </Pressable>
        </Pressable>
      </Modal>

      <Modal visible={!!activeMatch} transparent animationType="fade">
        <Pressable style={styles.modalBackdrop} onPress={() => setActiveMatch(null)}>
          <Pressable style={styles.modalCard} onPress={() => { }}>
            <Text style={styles.h3}>Online Suggestion</Text>
            {activeMatch ? (
              <>
                <Text style={styles.body}>{activeMatch.message}</Text>
                {activeMatch.context ? (
                  <Text style={styles.sub}>
                    {activeMatch.context.text}
                  </Text>
                ) : null}
                {activeMatch.replacements?.length ? (
                  <Text style={styles.body}>
                    Suggestions: {activeMatch.replacements.slice(0, 6).map((r) => r.value).join(', ')}
                  </Text>
                ) : null}
                {(() => {
                  const ctx = activeMatch.context || {};
                  const bad = ctx.text && typeof ctx.offset === 'number'
                    ? ctx.text.slice(ctx.offset, ctx.offset + ctx.length)
                    : '';
                  const entry = bad ? getWordEntry(bad.toLowerCase()) : null;
                  const synonyms = entry?.synonyms?.slice(0, 6) || [];
                  return synonyms.length ? (
                    <Text style={styles.body}>Synonyms: {synonyms.join(', ')}</Text>
                  ) : null;
                })()}
              </>
            ) : null}
            <View style={styles.modalActions}>
              <Button
                label="Accept"
                onPress={() => {
                  setMatchState(activeMatch, 'accepted');
                  setActiveMatch(null);
                }}
              />
              <Button
                label="Reject"
                variant="secondary"
                onPress={() => {
                  setMatchState(activeMatch, 'rejected');
                  setActiveMatch(null);
                }}
              />
              <Button label="Close" variant="ghost" onPress={() => setActiveMatch(null)} />
            </View>
          </Pressable>
        </Pressable>
      </Modal>
    </Screen>
  );
}

const styles = StyleSheet.create({
  content: {
    paddingBottom: spacing.xl
  },
  h1: {
    fontSize: typography.h1,
    fontFamily: typography.fontHeadline,
    color: colors.text,
    marginBottom: spacing.md
  },
  h3: {
    fontSize: typography.h3,
    fontFamily: typography.fontHeadline,
    marginBottom: spacing.sm
  },
  h4: {
    fontSize: typography.body,
    fontFamily: typography.fontHeadline,
    marginTop: spacing.sm,
    marginBottom: spacing.xs
  },
  body: {
    fontSize: typography.body,
    fontFamily: typography.fontBody
  },
  sub: {
    fontSize: typography.small,
    color: colors.muted,
    marginBottom: spacing.sm
  },
  link: {
    color: colors.primary,
    fontSize: typography.small,
    marginBottom: spacing.sm,
    textDecorationLine: 'underline'
  },
  inlineText: {
    lineHeight: 22
  },
  inlinePress: {
    lineHeight: 22
  },
  tag_ww: {
    backgroundColor: '#FDE2E2'
  },
  tag_sv: {
    backgroundColor: '#FFF3CD'
  },
  tag_cap: {
    backgroundColor: '#E2F0FF'
  },
  tag_wo: {
    backgroundColor: '#E7F7E2'
  },
  tag_art: {
    backgroundColor: '#EDE7FF'
  },
  tag_punc: {
    backgroundColor: '#F2F2F2'
  },
  tag_tense: {
    backgroundColor: '#FFE6E6'
  },
  tag_prep: {
    backgroundColor: '#E6FFF5'
  },
  tag_pron: {
    backgroundColor: '#FFF1E6'
  },
  tag_rep: {
    backgroundColor: '#E8E6FF'
  },
  legend: {
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
    gap: spacing.xs
  },
  chips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: spacing.sm
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs
  },
  legendSwatch: {
    width: 14,
    height: 14,
    borderRadius: 4
  },
  legendLabel: {
    fontSize: typography.small,
    color: colors.muted
  },
  card: {
    marginBottom: spacing.lg
  },
  block: {
    marginTop: spacing.sm
  },
  onlineItem: {
    padding: spacing.sm,
    borderRadius: 10,
    backgroundColor: colors.surface,
    marginTop: spacing.sm
  },
  resultItem: {
    padding: spacing.sm,
    borderRadius: 10,
    backgroundColor: colors.surface,
    marginTop: spacing.sm
  },
  online_grammar: {
    backgroundColor: '#FFE9D6'
  },
  online_vocab: {
    backgroundColor: '#E6F4FF'
  },
  online_mechanics: {
    backgroundColor: '#E9F7E3'
  },
  onlineActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
    marginBottom: spacing.sm
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    padding: spacing.lg
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: spacing.lg
  },
  modalActions: {
    marginTop: spacing.md,
    gap: spacing.xs
  },
  saveRow: {
    marginTop: spacing.md
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: typography.body,
    color: colors.text,
    marginBottom: spacing.sm
  },
  // Rubric progress bar styles
  totalScoreRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: spacing.xs,
    marginBottom: spacing.md,
    backgroundColor: colors.surface,
    padding: spacing.md,
    borderRadius: 12,
  },
  totalScoreNum: {
    fontSize: 42,
    fontFamily: typography.fontHeadline,
    color: colors.primary,
  },
  totalScoreDenom: {
    fontSize: typography.h3,
    color: colors.muted,
    fontFamily: typography.fontHeadline,
  },
  totalScoreLabel: {
    fontSize: typography.body,
    color: colors.text,
    flex: 1,
    textAlign: 'right',
    fontFamily: typography.fontHeadline,
  },
  rubricItem: {
    marginBottom: spacing.md,
  },
  rubricLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  rubricName: {
    fontSize: typography.body,
    fontFamily: typography.fontHeadline,
    color: colors.text,
  },
  rubricScore: {
    fontSize: typography.body,
    fontFamily: typography.fontHeadline,
    color: colors.primary,
  },
  progressTrack: {
    height: 8,
    backgroundColor: colors.surface,
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 4,
  },
  progressFill: {
    height: '100%',
    borderRadius: 4,
  },
  rubricDesc: {
    fontSize: typography.small,
    color: colors.muted,
  },
  // Revised / improved version styles
  revisedCard: {
    borderWidth: 2,
    borderColor: colors.primary,
  },
  revisedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  revisedText: {
    fontSize: typography.body,
    color: colors.text,
    lineHeight: 24,
    fontFamily: typography.fontBody,
  },
  copyBtn: {
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.secondary,
  },
  copyBtnText: {
    fontSize: typography.small,
    color: colors.primary,
    fontFamily: typography.fontHeadline,
  },
});
