import json

PATH = '/Users/yasinkaya/Desktop/BUEPT-APP/BUEPTApp/data/academic_wordlist.json'

# AWL is 570 words. I'll populate them in batches to ensure quality.
# I'll use list of common AWL words for BUEPT.
# This is a large set. I'll include Sublist 1-10.

AWL_FULL = [
    # Sublist 1
    {"word": "analyze", "definition": "To examine in detail to understand or explain.", "level": "B2"},
    {"word": "approach", "definition": "A way of dealing with something.", "level": "B2"},
    {"word": "area", "definition": "A particular part or section.", "level": "B2"},
    {"word": "assess", "definition": "To evaluate or estimate the nature, ability, or quality of.", "level": "B2"},
    {"word": "assume", "definition": "To suppose to be the case, without proof.", "level": "B2"},
    {"word": "authority", "definition": "The power or right to give orders or make decisions.", "level": "B2"},
    {"word": "available", "definition": "Able to be used or obtained.", "level": "B2"},
    {"word": "benefit", "definition": "An advantage or profit gained from something.", "level": "B2"},
    {"word": "concept", "definition": "An abstract idea or a general notion.", "level": "B2"},
    {"word": "consist", "definition": "To be composed or made up of.", "level": "B2"},
    {"word": "constitute", "definition": "To be a part of a whole.", "level": "C1"},
    {"word": "context", "definition": "The circumstances that form the setting for an event.", "level": "B2"},
    {"word": "contract", "definition": "A written or spoken agreement.", "level": "B2"},
    {"word": "create", "definition": "To bring something into existence.", "level": "B2"},
    {"word": "data", "definition": "Facts and statistics collected together for analysis.", "level": "B2"},
    {"word": "define", "definition": "To state or describe exactly the nature or scope of.", "level": "B2"},
    {"word": "derive", "definition": "To obtain something from a specified source.", "level": "B2"},
    {"word": "distribute", "definition": "To give shares of something; to scatter.", "level": "B2"},
    {"word": "economy", "definition": "The wealth and resources of a country or region.", "level": "B2"},
    {"word": "environment", "definition": "The surroundings or conditions in which a person lives.", "level": "B2"},
    {"word": "establish", "definition": "To set up on a firm or permanent basis.", "level": "B2"},
    {"word": "estimate", "definition": "Roughly calculate or judge the value or quantity of.", "level": "B2"},
    {"word": "evident", "definition": "Plain or obvious; clearly seen or understood.", "level": "B2"},
    {"word": "export", "definition": "To send goods or services to another country for sale.", "level": "B2"},
    {"word": "factor", "definition": "A circumstance or influence that contributes to a result.", "level": "B2"},
    {"word": "finance", "definition": "The management of large amounts of money.", "level": "B2"},
    {"word": "formula", "definition": "A mathematical relationship or rule.", "level": "B2"},
    {"word": "function", "definition": "An activity or purpose natural to or intended for a person or thing.", "level": "B2"},
    {"word": "identify", "definition": "To establish or indicate who or what someone or something is.", "level": "B2"},
    {"word": "income", "definition": "Money received on a regular basis for work or through investments.", "level": "B2"},
    {"word": "indicate", "definition": "To point out or show.", "level": "B2"},
    {"word": "individual", "definition": "Single; separate.", "level": "B1"},
    {"word": "interpret", "definition": "To explain the meaning of information or actions.", "level": "B2"},
    {"word": "involve", "definition": "To include or contain as a necessary part.", "level": "B1"},
    {"word": "issue", "definition": "An important topic or problem for debate or discussion.", "level": "B2"},
    {"word": "labor", "definition": "Work, especially hard physical work.", "level": "B2"},
    {"word": "legal", "definition": "Of, based on, or concerned with the law.", "level": "B2"},
    {"word": "legislate", "definition": "To make or enact laws.", "level": "C1"},
    {"word": "major", "definition": "Important, serious, or significant.", "level": "B1"},
    {"word": "method", "definition": "A particular form of procedure for accomplishing something.", "level": "B2"},
    {"word": "occur", "definition": "To happen or take place.", "level": "B2"},
    {"word": "percent", "definition": "One part in every hundred.", "level": "B1"},
    {"word": "period", "definition": "A length or portion of time.", "level": "B1"},
    {"word": "policy", "definition": "A course or principle of action adopted by an organization.", "level": "B2"},
    {"word": "principle", "definition": "A fundamental truth or proposition.", "level": "B2"},
    {"word": "proceed", "definition": "To begin or continue a course of action.", "level": "B2"},
    {"word": "process", "definition": "A series of actions or steps taken in order to achieve an end.", "level": "B2"},
    {"word": "require", "definition": "To need for a particular purpose.", "level": "B1"},
    {"word": "research", "definition": "The systematic investigation into and study of materials.", "level": "B2"},
    {"word": "respond", "definition": "To say or do something as a reaction to something.", "level": "B2"},
    {"word": "role", "definition": "An actor's part in a play, movie, etc.; a function.", "level": "B1"},
    {"word": "section", "definition": "Any of the more or less distinct parts into which something is divided.", "level": "B2"},
    {"word": "sector", "definition": "An area or portion that is distinct from others.", "level": "B2"},
    {"word": "significant", "definition": "Sufficiently great or important to be worthy of attention.", "level": "B2"},
    {"word": "similar", "definition": "Resembling without being identical.", "level": "B1"},
    {"word": "source", "definition": "A place, person, or thing from which something comes.", "level": "B2"},
    {"word": "specific", "definition": "Clearly defined or identified.", "level": "B2"},
    {"word": "structure", "definition": "The arrangement of and relations between the parts of something complex.", "level": "B2"},
    {"word": "theory", "definition": "A system of ideas intended to explain something.", "level": "B2"},
    {"word": "vary", "definition": "To differ in size, amount, degree, or nature.", "level": "B2"},

    # Sublist 2
    {"word": "achieve", "definition": "To successfully bring about or reach by effort, skill, or courage.", "level": "B2"},
    {"word": "acquire", "definition": "To buy or obtain for oneself.", "level": "B2"},
    {"word": "administrate", "definition": "To manage and be responsible for the running of a business or organization.", "level": "C1"},
    {"word": "affect", "definition": "To have an effect on; make a difference to.", "level": "B2"},
    {"word": "appropriate", "definition": "Suitable or proper in the circumstances.", "level": "B2"},
    {"word": "aspect", "definition": "A particular part or feature of something.", "level": "B2"},
    {"word": "assist", "definition": "To help someone, typically by doing a share of the work.", "level": "B1"},
    {"word": "category", "definition": "A class or division of people or things regarded as having particular shared characteristics.", "level": "B1"},
    {"word": "chapter", "definition": "A main division of a book, typically with a number or title.", "level": "A2"},
    {"word": "commission", "definition": "An instruction, command, or duty given to a person or group.", "level": "B2"},
    {"word": "community", "definition": "A group of people living in the same place or having a particular characteristic in common.", "level": "B1"},
    {"word": "complex", "definition": "Consisting of many different and connected parts.", "level": "B2"},
    {"word": "compute", "definition": "To reckon or calculate a quantity or amount.", "level": "B2"},
    {"word": "conclude", "definition": "To bring something to an end.", "level": "B2"},
    {"word": "conduct", "definition": "The manner in which a person behaves; to organize and carry out.", "level": "B2"},
    {"word": "consequent", "definition": "Following as a result or effect.", "level": "C1"},
    {"word": "construct", "definition": "To build or erect something.", "level": "B2"},
    {"word": "consume", "definition": "To eat, drink, or use up.", "level": "B2"},
    {"word": "credit", "definition": "The ability of a customer to obtain goods or services before payment, based on the trust that payment will be made in the future.", "level": "B2"},
    {"word": "culture", "definition": "The arts and other manifestations of human intellectual achievement regarded collectively.", "level": "B1"},
    {"word": "design", "definition": "A plan or drawing produced to show the look and function or workings of a building, garment, or other object before it is built or made.", "level": "B1"},
    {"word": "distinct", "definition": "Recognizably different in nature from something else of a similar type.", "level": "B2"},
    {"word": "element", "definition": "A part or aspect of something abstract, especially one that is essential or characteristic.", "level": "B2"},
    {"word": "equate", "definition": "To consider one thing to be the same as or equivalent to another.", "level": "B2"},
    {"word": "evaluate", "definition": "To form an idea of the amount, number, or value of; assess.", "level": "B2"},
    {"word": "feature", "definition": "A distinctive attribute or aspect of something.", "level": "B2"},
    {"word": "final", "definition": "Coming at the end of a series.", "level": "A1"},
    {"word": "focus", "definition": "The center of interest or activity.", "level": "B1"},
    {"word": "impact", "definition": "The action of one object coming forcibly into contact with another; a marked effect or influence.", "level": "B2"},
    {"word": "institute", "definition": "A society or organization having a particular object or common factor.", "level": "B2"},
    {"word": "invest", "definition": "To expend money with the expectation of achieving a profit.", "level": "B2"},
    {"word": "item", "definition": "An individual article or unit, especially one that is part of a list, collection, or set.", "level": "B1"},
    {"word": "journal", "definition": "A newspaper or magazine that deals with a particular subject or professional activity.", "level": "B2"},
    {"word": "maintain", "definition": "To cause or enable a condition or state of affairs to continue.", "level": "B2"},
    {"word": "normal", "definition": "Conforming to a standard; usual, typical, or expected.", "level": "A1"},
    {"word": "obtain", "definition": "To get, acquire, or secure.", "level": "B2"},
    {"word": "participate", "definition": "To take part in an action or endeavor.", "level": "B2"},
    {"word": "perceive", "definition": "To become aware or conscious of something; come to realize or understand.", "level": "B2"},
    {"word": "positive", "definition": "Constructive, optimistic, or confident.", "level": "B1"},
    {"word": "potential", "definition": "Having or showing the capacity to become or develop into something in the future.", "level": "B2"},
    {"word": "previous", "definition": "Existing or occurring before in time or order.", "level": "B1"},
    {"word": "primary", "definition": "Of chief importance; principal.", "level": "B2"},
    {"word": "purchase", "definition": "To acquire something by paying for it; buy.", "level": "B2"},
    {"word": "range", "definition": "The area of variation between upper and lower limits on a particular scale.", "level": "B2"},
    {"word": "region", "definition": "An area or division, especially part of a country or the world having definable characteristics but not always fixed boundaries.", "level": "B1"},
    {"word": "regulate", "definition": "To control or maintain the rate or speed of a machine or process so that it operates properly.", "level": "B2"},
    {"word": "relevant", "definition": "Closely connected or appropriate to what is being done or considered.", "level": "B2"},
    {"word": "reside", "definition": "To have one's permanent home in a particular place.", "level": "B2"},
    {"word": "resource", "definition": "A stock or supply of money, materials, staff, and other assets that can be drawn on by a person or organization in order to function effectively.", "level": "B2"},
    {"word": "restrict", "definition": "To put a limit on; keep under control.", "level": "B1"},
    {"word": "secure", "definition": "To fix or attach something firmly so that it cannot be moved or lost.", "level": "B2"},
    {"word": "seek", "definition": "To attempt to find something.", "level": "B2"},
    {"word": "select", "definition": "To carefully choose as being the best or most suitable.", "level": "B2"},
    {"word": "site", "definition": "An area of ground on which a town, building, or monument is constructed.", "level": "B2"},
    {"word": "strategy", "definition": "A plan of action or policy designed to achieve a major or overall aim.", "level": "B2"},
    {"word": "survey", "definition": "To look carefully and thoroughly at someone or something, especially so as to appraise them.", "level": "B2"},
    {"word": "text", "definition": "A book or other written or printed work, regarded in terms of its content rather than its physical form.", "level": "B1"},
    {"word": "traditional", "definition": "Existing in or as part of a tradition; long-established.", "level": "B1"},
    {"word": "transfer", "definition": "To move from one place to another.", "level": "B2"},

    # Sublist 3
    {"word": "alternative", "definition": "Available as another possibility.", "level": "B2"},
    {"word": "circumstance", "definition": "A fact or condition connected with or relevant to an event or action.", "level": "B2"},
    {"word": "comment", "definition": "A verbal or written remark expressing an opinion or reaction.", "level": "B1"},
    {"word": "compensate", "definition": "To give someone something, typically money, in recognition of loss, suffering, or injury.", "level": "B2"},
    {"word": "component", "definition": "A part or element of a larger whole.", "level": "B2"},
    {"word": "consent", "definition": "Permission for something to happen or agreement to do something.", "level": "B2"},
    {"word": "considerable", "definition": "Notably large in size, amount, or extent.", "level": "B2"},
    {"word": "constant", "definition": "Occurring continuously over a period of time.", "level": "B2"},
    {"word": "constrain", "definition": "To compel or force someone toward a particular course of action.", "level": "C1"},
    {"word": "contribute", "definition": "To give something in order to help achieve or provide something.", "level": "B2"},
    {"word": "convene", "definition": "To come or bring together for a meeting or activity; assemble.", "level": "C1"},
    {"word": "coordinate", "definition": "To bring the different elements of a complex activity or organization into a harmonious or efficient relationship.", "level": "B2"},
    {"word": "core", "definition": "The tough central part of various fruits, containing the seeds; the central or most important part of something.", "level": "B2"},
    {"word": "corporate", "definition": "Relating to a corporation, especially a large company or group.", "level": "B2"},
    {"word": "correspond", "definition": "To have a close similarity; match or agree almost exactly.", "level": "B2"},
    {"word": "criteria", "definition": "A principle or standard by which something may be judged or decided.", "level": "B2"},
    {"word": "deduce", "definition": "To arrive at a fact or a conclusion by reasoning; draw as a logical conclusion.", "level": "B2"},
    {"word": "demonstrate", "definition": "To clearly show the existence or truth of something by giving proof or evidence.", "level": "B2"},
    {"word": "document", "definition": "A piece of written, printed, or electronic matter that provides information or evidence or that serves as an official record.", "level": "B1"},
    {"word": "dominate", "definition": "To have a commanding influence on; exercise control over.", "level": "B2"},
    {"word": "emphasis", "definition": "Special importance, value, or prominence given to something.", "level": "B2"},
    {"word": "ensure", "definition": "To make certain that something shall occur or be the case.", "level": "B2"},
    {"word": "exclude", "definition": "To deny someone access to or bar someone from a place, group, or privilege.", "level": "B2"},
    {"word": "framework", "definition": "An essential supporting structure of a building, vehicle, or object.", "level": "B2"},
    {"word": "fund", "definition": "A sum of money saved or made available for a particular purpose.", "level": "B2"},
    {"word": "illustrate", "definition": "To provide a book, newspaper, etc., with pictures.", "level": "B2"},
    {"word": "immigrate", "definition": "To come to live permanently in a foreign country.", "level": "B2"},
    {"word": "imply", "definition": "To strongly suggest the truth or existence of something not expressly stated.", "level": "B2"},
    {"word": "initial", "definition": "Existing or occurring at the beginning.", "level": "B2"},
    {"word": "instance", "definition": "An example or single occurrence of something.", "level": "B2"},
    {"word": "interact", "definition": "To act in such a way as to have an effect on another; communicate.", "level": "B2"},
    {"word": "justify", "definition": "To show or prove to be right or reasonable.", "level": "B2"},
    {"word": "layer", "definition": "A sheet, quantity, or thickness of material, typically one of several, covering a surface or forming a horizontal division.", "level": "B2"},
    {"word": "link", "definition": "A relationship between two things or situations, especially where one affects the other.", "level": "B1"},
    {"word": "locate", "definition": "To discover the exact place or position of.", "level": "B1"},
    {"word": "maximize", "definition": "To make as large or great as possible.", "level": "B2"},
    {"word": "minor", "definition": "Lesser in importance, seriousness, or significance.", "level": "B1"},
    {"word": "negate", "definition": "To nullify; make ineffective.", "level": "C1"},
    {"word": "outcome", "definition": "The way a thing turns out; a consequence.", "level": "B2"},
    {"word": "partner", "definition": "A person who takes part in an undertaking with another or others, especially in a business or company.", "level": "B1"},
    {"word": "philosophy", "definition": "The study of the fundamental nature of knowledge, reality, and existence.", "level": "B2"},
    {"word": "physical", "definition": "Relating to the body as opposed to the mind.", "level": "B1"},
    {"word": "proportion", "definition": "A part, share, or number considered in comparative relation to a whole.", "level": "B2"},
    {"word": "publish", "definition": "To prepare and issue a book, journal, piece of music, or other work for public sale.", "level": "B1"},
    {"word": "react", "definition": "To respond in a particular way to something.", "level": "B2"},
    {"word": "register", "definition": "An official list or record, for example of names of inhabitants of a region.", "level": "B2"},
    {"word": "rely", "definition": "To depend on with full trust or confidence.", "level": "B2"},
    {"word": "remove", "definition": "To take something away or off from the position occupied.", "level": "B1"},
    {"word": "scheme", "definition": "A large-scale systematic plan or arrangement for attaining some particular object or putting a particular idea into effect.", "level": "B2"},
    {"word": "sequence", "definition": "A particular order in which related events, movements, or things follow each other.", "level": "B2"},
    {"word": "sex", "definition": "The state of being male or female.", "level": "B1"},
    {"word": "shift", "definition": "To move or cause to move from one place to another, especially over a short distance.", "level": "B1"},
    {"word": "specify", "definition": "To identify clearly and definitely.", "level": "B2"},
    {"word": "sufficient", "definition": "Enough; adequate.", "level": "B2"},
    {"word": "task", "definition": "A piece of work to be done or undertaken.", "level": "B1"},
    {"word": "technical", "definition": "Relating to a particular subject, art, or craft, or its techniques.", "level": "B2"},
    {"word": "technique", "definition": "A way of carrying out a particular task, especially the execution or performance of an artistic work or a scientific procedure.", "level": "B2"},
    {"word": "technology", "definition": "The application of scientific knowledge for practical purposes, especially in industry.", "level": "B1"},
    {"word": "valid", "definition": "Having a sound basis in logic or fact; reasonable or cogent.", "level": "B2"},
    {"word": "volume", "definition": "A book forming part of a work or series; the amount of space that a substance or object occupies.", "level": "B2"},

    # Sublist 4
    {"word": "access", "definition": "The means or opportunity to approach or enter a place.", "level": "B2"},
    {"word": "adequate", "definition": "Satisfactory or acceptable in quality or quantity.", "level": "B2"},
    {"word": "annual", "definition": "Occurring once every year.", "level": "B1"},
    {"word": "apparent", "definition": "Clearly visible or understood; obvious.", "level": "B2"},
    {"word": "approximate", "definition": "Close to the actual, but not completely accurate or exact.", "level": "B2"},
    {"word": "attitude", "definition": "A settled way of thinking or feeling about someone or something.", "level": "B1"},
    {"word": "attribute", "definition": "A quality or feature regarded as a characteristic or inherent part of someone or something.", "level": "B2"},
    {"word": "civil", "definition": "Relating to ordinary citizens and their concerns.", "level": "B2"},
    {"word": "code", "definition": "A system of words, letters, figures, or other symbols substituted for other words, letters, etc., especially for the purposes of secrecy.", "level": "B2"},
    {"word": "commitment", "definition": "The state or quality of being dedicated to a cause, activity, etc.", "level": "B2"},
    {"word": "communication", "definition": "The imparting or exchanging of information or news.", "level": "B1"},
    {"word": "concentration", "definition": "The action or power of focusing one's attention or mental effort.", "level": "B2"},
    {"word": "conference", "definition": "A formal meeting for discussion.", "level": "B2"},
    {"word": "contrast", "definition": "The state of being strikingly different from something else in juxtaposition or close association.", "level": "B2"},
    {"word": "cycle", "definition": "A series of events that are regularly repeated in the same order.", "level": "B1"},
    {"word": "debate", "definition": "A formal discussion on a particular topic in a public meeting or legislative assembly.", "level": "B2"},
    {"word": "despite", "definition": "In spite of.", "level": "B2"},
    {"word": "dimension", "definition": "A measurable extent of some kind, such as length, breadth, depth, or height.", "level": "B2"},
    {"word": "domestic", "definition": "Relating to the running of a home or to family relations.", "level": "B2"},
    {"word": "emerge", "definition": "To move out of or away from something and come into view.", "level": "B2"},
    {"word": "error", "definition": "A mistake.", "level": "B1"},
    {"word": "ethnic", "definition": "Relating to a population subgroup with a common national or cultural tradition.", "level": "B2"},
    {"word": "goal", "definition": "An aim or desired result.", "level": "B1"},
    {"word": "grant", "definition": "To agree to give or allow something requested to.", "level": "B2"},
    {"word": "hence", "definition": "As a consequence; for this reason.", "level": "B2"},
    {"word": "hypothesis", "definition": "A supposition or proposed explanation made on the basis of limited evidence as a starting point for further investigation.", "level": "C1"},
    {"word": "implement", "definition": "A tool, utensil, or other piece of equipment, especially as used for a particular purpose.", "level": "B2"},
    {"word": "implicate", "definition": "To show someone to be involved in a crime.", "level": "C1"},
    {"word": "impose", "definition": "To force something welcome or unfamiliar to be accepted or put in place.", "level": "B2"},
    {"word": "index", "definition": "An alphabetical list of names, subjects, etc., with references to the places where they occur, typically found at the end of a book.", "level": "B2"},
    {"word": "inevitable", "definition": "Certain to happen; unavoidable.", "level": "B2"},
    {"word": "inflict", "definition": "To cause something unpleasant or painful to be suffered by someone or something.", "level": "C1"},
    {"word": "internal", "definition": "Of or situated on the inside.", "level": "B2"},
    {"word": "investigate", "definition": "To carry out a systematic or formal inquiry to discover and examine the facts of an incident, allegation, etc., so as to establish the truth.", "level": "B2"},
    {"word": "job", "definition": "A paid position of regular employment.", "level": "A1"},
    {"word": "label", "definition": "A small piece of paper, fabric, plastic, or similar material attached to an object and giving information about it.", "level": "B1"},
    {"word": "mechanism", "definition": "A system of parts working together in a machine; a piece of machinery.", "level": "B2"},
    {"word": "obvious", "definition": "Easily perceived or understood; clear, self-evident, or apparent.", "level": "B1"},
    {"word": "occupy", "definition": "To reside or have one's place of business in a building.", "level": "B2"},
    {"word": "option", "definition": "A thing that is or may be chosen.", "level": "B1"},
    {"word": "output", "definition": "The amount of something produced by a person, machine, or industry.", "level": "B2"},
    {"word": "overall", "definition": "Taking everything into account.", "level": "B2"},
    {"word": "parallel", "definition": "Side by side and having the same distance continuously between them.", "level": "B2"},
    {"word": "parameter", "definition": "A numerical or other measurable factor forming one of a set that defines a system or sets the conditions of its operation.", "level": "C1"},
    {"word": "phase", "definition": "A distinct period or stage in a series of events or a process of change or development.", "level": "B2"},
    {"word": "predict", "definition": "To say or estimate that a specified thing will happen in the future or will be a consequence of something.", "level": "B1"},
    {"word": "prior", "definition": "Existing or coming before in time, order, or importance.", "level": "B2"},
    {"word": "principal", "definition": "First in order of importance; main.", "level": "B2"},
    {"word": "professional", "definition": "Relating to or connected with a profession.", "level": "B2"},
    {"word": "project", "definition": "An individual or collaborative enterprise that is carefully planned and designed to achieve a particular aim.", "level": "B1"},
    {"word": "promote", "definition": "To further the progress of something, especially a cause, venture, or aim; support or actively encourage.", "level": "B2"},
    {"word": "regime", "definition": "A government, especially an authoritarian one.", "level": "C1"},
    {"word": "resolution", "definition": "A firm decision to do or not to do something.", "level": "B2"},
    {"word": "retain", "definition": "To continue to have something; keep possession of.", "level": "B2"},
    {"word": "series", "definition": "A number of things, events, or people of a similar kind or related nature coming one after another.", "level": "B1"},
    {"word": "statistics", "definition": "The practice or science of collecting and analyzing numerical data in large quantities.", "level": "B2"},
    {"word": "status", "definition": "The relative social, professional, or other standing of someone or something.", "level": "B2"},
    {"word": "stress", "definition": "Pressure or tension exerted on a material object.", "level": "B1"},
    {"word": "subsequent", "definition": "Coming after something in time; following.", "level": "B2"},
    {"word": "sum", "definition": "A particular amount of money.", "level": "B1"},
    {"word": "summary", "definition": "A brief statement or account of the main points of something.", "level": "B2"},
    {"word": "undertake", "definition": "To commit oneself to and begin a venture or task; embark on.", "level": "B2"},

    # Sublist 5
    {"word": "academic", "definition": "Relating to education and scholarship.", "level": "B2"},
    {"word": "adjustment", "definition": "A small alteration or movement made to achieve a desired fit, appearance, or result.", "level": "B2"},
    {"word": "appropriate", "definition": "Suitable or proper in the circumstances.", "level": "B2"},
    {"word": "aspect", "definition": "A particular part or feature of something.", "level": "B2"},
    {"word": "assist", "definition": "To help someone, typically by doing a share of the work.", "level": "B1"},
    {"word": "category", "definition": "A class or division of people or things regarded as having particular shared characteristics.", "level": "B1"},
    {"word": "challenge", "definition": "A call to take part in a contest or competition, especially a duel.", "level": "B1"},
    {"word": "clause", "definition": "A unit of grammatical organization next below the sentence in rank and in traditional grammar said to consist of a subject and a predicate.", "level": "B2"},
    {"word": "common", "definition": "Occurring, found, or done often; prevalent.", "level": "A1"},
    {"word": "complex", "definition": "Consisting of many different and connected parts.", "level": "B2"},
    {"word": "conclusion", "definition": "The end or finish of an event or process.", "level": "B2"},
    {"word": "conflict", "definition": "A serious disagreement or argument, typically a protracted one.", "level": "B2"},
    {"word": "consult", "definition": "To seek information or advice from someone with expertise in a particular area.", "level": "B2"},
    {"word": "contact", "definition": "The state or condition of physical touching.", "level": "B2"},
    {"word": "contrast", "definition": "The state of being strikingly different from something else in juxtaposition or close association.", "level": "B2"},
    {"word": "customer", "definition": "A person or organization that buys goods or services from a store or business.", "level": "A2"},
    {"word": "definition", "definition": "A statement of the exact meaning of a word, especially in a dictionary.", "level": "B2"},
    {"word": "demonstrate", "definition": "To clearly show the existence or truth of something by giving proof or evidence.", "level": "B2"},
    {"word": "design", "definition": "A plan or drawing produced to show the look and function or workings of a building, garment, or other object before it is built or made.", "level": "B1"},
    {"word": "despite", "definition": "In spite of.", "level": "B2"},
    {"word": "dimension", "definition": "A measurable extent of some kind, such as length, breadth, depth, or height.", "level": "B2"},
    {"word": "document", "definition": "A piece of written, printed, or electronic matter that provides information or evidence or that serves as an official record.", "level": "B1"},
    {"word": "domestic", "definition": "Relating to the running of a home or to family relations.", "level": "B2"},
    {"word": "emphasize", "definition": "To give special importance or prominence to something in speaking or writing.", "level": "B2"},
    {"word": "enable", "definition": "To give someone or something the authority or means to do something.", "level": "B2"},
    {"word": "energy", "definition": "The strength and vitality required for sustained physical or mental activity.", "level": "B1"},
    {"word": "enforce", "definition": "To compel observance of or compliance with a law, rule, or obligation.", "level": "C1"},
    {"word": "entity", "definition": "A thing with distinct and independent existence.", "level": "C1"},
    {"word": "equivalent", "definition": "Equal in value, amount, function, meaning, etc.", "level": "B2"},
    {"word": "error", "definition": "A mistake.", "level": "B1"},
    {"word": "establish", "definition": "To set up on a firm or permanent basis.", "level": "B2"},
    {"word": "evaluate", "definition": "To form an idea of the amount, number, or value of; assess.", "level": "B2"},
    {"word": "evidence", "definition": "The available body of facts or information indicating whether a belief or proposition is true or valid.", "level": "B2"},
    {"word": "exclude", "definition": "To deny someone access to or bar someone from a place, group, or privilege.", "level": "B2"},
    {"word": "expand", "definition": "To become or make larger or more extensive.", "level": "B2"},
    {"word": "expose", "definition": "To make something visible by uncovering it.", "level": "B2"},
    {"word": "external", "definition": "Belonging to or forming the outer surface or structure of something.", "level": "B2"},
    {"word": "facilitate", "definition": "To make an action or process easy or easier.", "level": "C1"},
    {"word": "factor", "definition": "A circumstance or influence that contributes to a result.", "level": "B2"},
    {"word": "feature", "definition": "A distinctive attribute or aspect of something.", "level": "B2"},
    {"word": "fee", "definition": "A payment made to a professional person or public body in exchange for advice or services.", "level": "B1"},
    {"word": "focus", "definition": "The center of interest or activity.", "level": "B1"},
    {"word": "format", "definition": "The way in which something is arranged or set out.", "level": "B2"},
    {"word": "function", "definition": "An activity or purpose natural to or intended for a person or thing.", "level": "B2"},
    {"word": "generate", "definition": "To cause something, especially an emotion or situation, to arise or come about.", "level": "B2"},
    {"word": "generation", "definition": "All of the people born and living at about the same time.", "level": "B2"},
    {"word": "grant", "definition": "To agree to give or allow something requested to.", "level": "B2"},
    {"word": "guarantee", "definition": "A formal promise or assurance that certain conditions will be fulfilled.", "level": "B2"},
    {"word": "hypothesis", "definition": "A supposition or proposed explanation made on the basis of limited evidence as a starting point for further investigation.", "level": "C1"},
    {"word": "identify", "definition": "To establish or indicate who or what someone or something is.", "level": "B2"},
    {"word": "ignore", "definition": "To refuse to take notice of or acknowledge.", "level": "B1"},
    {"word": "image", "definition": "A representation of the external form of a person or thing in art.", "level": "B1"},
    {"word": "impact", "definition": "The action of one object coming forcibly into contact with another; a marked effect or influence.", "level": "B2"},
    {"word": "implement", "definition": "A tool, utensil, or other piece of equipment, especially as used for a particular purpose.", "level": "B2"},
    {"word": "implicate", "definition": "To show someone to be involved in a crime.", "level": "C1"},
    {"word": "implicit", "definition": "Implied though not plainly expressed.", "level": "C1"},
    {"word": "imply", "definition": "To strongly suggest the truth or existence of something not expressly stated.", "level": "B2"},
    {"word": "impose", "definition": "To force something welcome or unfamiliar to be accepted or put in place.", "level": "B2"},
    {"word": "incentive", "definition": "A thing that motivates or encourages one to do something.", "level": "B2"},
    {"word": "induce", "definition": "To succeed in persuading or influencing someone to do something.", "level": "C1"},
    {"word": "infer", "definition": "To deduce or conclude information from evidence and reasoning rather than from explicit statements.", "level": "C1"},
]

# Write the first 5 sublists (approx 280+ words)
with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(AWL_FULL, f, indent=2)

print(f"Expanded AWL to {len(AWL_FULL)} entries.")
